# Generated by Django 3.2.4 on 2021-06-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='game_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='victory_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
