# Generated by Django 3.2.4 on 2021-07-02 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20210620_1308'),
        ('climax_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climaxprofile',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='stats.profile'),
        ),
        migrations.CreateModel(
            name='ClimaxIngestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('climax_amount', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eater', to='climax_tracker.climaxprofile')),
            ],
        ),
    ]
