# Generated by Django 3.2.4 on 2021-07-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climax_tracker', '0003_auto_20210702_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='motive',
            field=models.TextField(blank=True, null=True),
        ),
    ]
