# Generated by Django 3.2.4 on 2021-07-09 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20210620_1308'),
        ('climax_tracker', '0005_climaxprofile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climaxprofile',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='stats.profile'),
            preserve_default=False,
        ),
    ]
