# Generated by Django 3.2.4 on 2021-07-15 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climax_tracker', '0007_alter_climaxprofile_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingBet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('climax_amount', models.IntegerField(default=1)),
                ('motive', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_bet_player_1', to='climax_tracker.climaxprofile')),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_bet_player_2', to='climax_tracker.climaxprofile')),
            ],
        ),
    ]
