# Generated by Django 3.1.7 on 2021-06-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('french_name', models.CharField(blank=True, max_length=50, null=True)),
                ('english_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='mage',
            constraint=models.UniqueConstraint(fields=('french_name',), name='unique_brand_french_name'),
        ),
        migrations.AddConstraint(
            model_name='mage',
            constraint=models.UniqueConstraint(fields=('english_name',), name='unique_brand_english_name'),
        ),
    ]
