# Generated by Django 3.1.7 on 2021-06-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nemesis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('french_name', models.CharField(blank=True, max_length=50, null=True)),
                ('english_name', models.CharField(blank=True, max_length=50, null=True)),
                ('difficulty', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='mage',
            name='unique_brand_french_name',
        ),
        migrations.RemoveConstraint(
            model_name='mage',
            name='unique_brand_english_name',
        ),
        migrations.AddConstraint(
            model_name='mage',
            constraint=models.UniqueConstraint(fields=('french_name',), name='unique_mage_french_name'),
        ),
        migrations.AddConstraint(
            model_name='mage',
            constraint=models.UniqueConstraint(fields=('english_name',), name='unique_mage_english_name'),
        ),
        migrations.AddConstraint(
            model_name='nemesis',
            constraint=models.UniqueConstraint(fields=('french_name',), name='unique_nemesis_french_name'),
        ),
        migrations.AddConstraint(
            model_name='nemesis',
            constraint=models.UniqueConstraint(fields=('english_name',), name='unique_nemesis_english_name'),
        ),
    ]
