# Generated by Django 3.1.7 on 2021-06-09 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aeon', '0003_auto_20210609_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_turn', models.IntegerField(blank=True, null=True)),
                ('is_win', models.BooleanField(default=False)),
                ('date_played', models.DateTimeField(auto_now_add=True)),
                ('cards_in_market', models.ManyToManyField(blank=True, to='aeon.Card')),
                ('mage', models.ManyToManyField(blank=True, to='aeon.Mage')),
                ('nemesis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aeon.nemesis')),
            ],
        ),
    ]
