# Generated by Django 3.1.7 on 2021-06-09 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aeon', '0004_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gem',
            old_name='ether_win',
            new_name='ether_gain',
        ),
    ]
