# Generated by Django 3.2.4 on 2021-06-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
        ('aeon', '0005_auto_20210609_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(blank=True, to='stats.Profile'),
        ),
    ]
