# Generated by Django 3.2.4 on 2021-06-09 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aeon', '0006_game_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('french_name', models.CharField(blank=True, max_length=50, null=True)),
                ('english_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='extension',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aeon.extension'),
        ),
        migrations.AddField(
            model_name='mage',
            name='extension',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aeon.extension'),
        ),
        migrations.AddField(
            model_name='nemesis',
            name='extension',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aeon.extension'),
        ),
    ]
