# Generated by Django 3.2.4 on 2021-06-09 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aeon', '0007_auto_20210609_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='extension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aeon.extension'),
        ),
        migrations.AlterField(
            model_name='mage',
            name='extension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aeon.extension'),
        ),
        migrations.AlterField(
            model_name='nemesis',
            name='extension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aeon.extension'),
        ),
    ]
