# Generated by Django 3.2.4 on 2021-06-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeon', '0009_gem_ether_maximum_gain'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='can_destroy_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spell',
            name='overtime_effect',
            field=models.BooleanField(default=False),
        ),
    ]
