# Generated by Django 3.2.4 on 2021-06-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeon', '0010_auto_20210609_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='maximum_damage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
