# Generated by Django 3.2.4 on 2021-06-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeon', '0011_spell_maximum_damage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='number_of_turn',
            field=models.IntegerField(blank=True, help_text='Optional', null=True),
        ),
    ]
