# Generated by Django 3.2.4 on 2021-06-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
        ('aeon', '0012_alter_game_number_of_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='defeat_type',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('GRAVEHOLD_DEATH', 'Gravehold died'), ('MAGE_DEATH', 'All Mages Died'), ('SPECIAL_NEMESIS_DEFEAT', 'Nemesis special win rule')], default='UNKNOWN', max_length=22),
        ),
        migrations.AddField(
            model_name='game',
            name='gravehold_hit_point',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gravehold HP'),
        ),
        migrations.AddField(
            model_name='game',
            name='mages_hit_point',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Mage HP'),
        ),
        migrations.AddField(
            model_name='game',
            name='nemesis_hit_point',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nemesis HP'),
        ),
        migrations.AddField(
            model_name='game',
            name='number_of_exhausted_mage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total number of mage exhausted'),
        ),
        migrations.AddField(
            model_name='game',
            name='victory_type',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('NEMESIS_KILL', 'Nemesis is killed'), ('NEMESIS_DECK_EMPTY', 'Nemesis deck is empty')], default='UNKNOWN', max_length=19),
        ),
        migrations.AlterField(
            model_name='game',
            name='cards_in_market',
            field=models.ManyToManyField(blank=True, help_text='All the available cards', to='aeon.Card', verbose_name='Cards'),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_win',
            field=models.BooleanField(default=False, verbose_name='Victory'),
        ),
        migrations.AlterField(
            model_name='game',
            name='number_of_turn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(blank=True, help_text='All the human players (Including you)', to='stats.Profile'),
        ),
    ]
