# Generated by Django 3.2.4 on 2021-06-11 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aeon', '0013_auto_20210610_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relic',
            name='card_ptr',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='card_ptr',
        ),
        migrations.DeleteModel(
            name='Gem',
        ),
        migrations.DeleteModel(
            name='Relic',
        ),
        migrations.DeleteModel(
            name='Spell',
        ),
    ]
