# Generated by Django 3.2.4 on 2021-06-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeon', '0015_auto_20210611_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='gravehold_heal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='player_heal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
