# Generated by Django 3.2.4 on 2021-06-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeon', '0016_auto_20210611_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='breach_focus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='gravehold_maximum_heal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='player_maximum_heal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
