# Generated by Django 3.2.4 on 2021-06-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeon', '0017_auto_20210611_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='game_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='win_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mage',
            name='game_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mage',
            name='win_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nemesis',
            name='game_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nemesis',
            name='win_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
