# Generated by Django 3.2.4 on 2021-06-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeon', '0018_auto_20210614_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='number_of_mage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
