# Generated by Django 3.2.4 on 2021-06-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeon', '0020_game_game_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='nemesis',
            name='total_hp',
            field=models.IntegerField(blank=True, default=70, null=True),
        ),
    ]
