# Generated by Django 3.2.4 on 2021-06-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeon', '0021_nemesis_total_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='total_damage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='total_maximum_damage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
