# Generated by Django 3.2.4 on 2021-06-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeon', '0022_auto_20210619_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='average_ether_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
