# Generated by Django 3.1 on 2020-09-15 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorDayEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_wall_climbed', models.IntegerField(blank=True, null=True)),
                ('grade', models.CharField(choices=[('Orange', 'Orange'), ('Green', 'Green'), ('Blue', 'Blue'), ('Red', 'Red')], max_length=12)),
                ('day', models.DateField(default=datetime.datetime(2020, 9, 15, 9, 38, 53, 184375))),
            ],
        ),
    ]
