# Generated by Django 3.1 on 2020-09-15 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boulder_stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colordayentry',
            name='day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
