# Generated by Django 3.1 on 2020-08-31 13:14

import data_storage.enums.brain_subzone
import data_storage.enums.sex
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrainQuantificationImport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('csv_file', models.FileField(upload_to='static/')),
                ('stage', models.CharField(choices=[('E12.5', 'E12_5'), ('E14.5', 'E14_5'), ('E16.5', 'E16_5'), ('E18.5', 'E18_5'), ('P0', 'P0'), ('P3', 'P3'), ('P5', 'P5'), ('P6', 'P6'), ('P7', 'P7'), ('P9', 'P9'), ('P14', 'P14'), ('P20', 'P20'), ('P60', 'P60')], max_length=20)),
                ('slice_thickness', models.IntegerField(blank=True, default=60, null=True)),
                ('zone', models.CharField(choices=[('Cortex', 'Cortex'), ('POA', 'POA'), ('Striatum', 'Striatum'), ('Hippocampus', 'Hippocampus'), ('Triangulo', 'Triangulo'), ('DG', 'DG')], max_length=12)),
            ],
        ),
        migrations.RenameField(
            model_name='brainquantification',
            old_name='Area',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='brainquantification',
            old_name='ki_min',
            new_name='ki_neg',
        ),
        migrations.AddField(
            model_name='brainquantification',
            name='brain_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='brainquantification',
            name='density',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brainquantification',
            name='density_ki67',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brainquantification',
            name='ki_neg_updated',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brainquantification',
            name='ki_pos_updated',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brainquantification',
            name='percent_ki_67',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brainquantification',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], default=data_storage.enums.sex.Sex['Unknown'], max_length=20),
        ),
        migrations.AddField(
            model_name='brainquantification',
            name='slice_thickness',
            field=models.IntegerField(blank=True, default=60, null=True),
        ),
        migrations.AddField(
            model_name='brainquantification',
            name='stage',
            field=models.CharField(choices=[('E12.5', 'E12_5'), ('E14.5', 'E14_5'), ('E16.5', 'E16_5'), ('E18.5', 'E18_5'), ('P0', 'P0'), ('P3', 'P3'), ('P5', 'P5'), ('P6', 'P6'), ('P7', 'P7'), ('P9', 'P9'), ('P14', 'P14'), ('P20', 'P20'), ('P60', 'P60')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='brainquantification',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brainquantification',
            name='sub_zone',
            field=models.CharField(choices=[('Empty', 'Empty'), ('MZ', 'MZ'), ('II_III', 'II_III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI')], default=data_storage.enums.brain_subzone.BrainSubZone['Empty'], max_length=12),
        ),
        migrations.AlterField(
            model_name='brainquantification',
            name='zone',
            field=models.CharField(choices=[('Cortex', 'Cortex'), ('POA', 'POA'), ('Striatum', 'Striatum'), ('Hippocampus', 'Hippocampus'), ('Triangulo', 'Triangulo'), ('DG', 'DG')], max_length=12),
        ),
    ]
