# Generated by Django 3.2.4 on 2021-07-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='app',
            field=models.CharField(choices=[('AEON', 'aeon'), ('CLIMAX_TRACKER', 'climax_tracker')], default='AEON', max_length=22),
        ),
    ]
