# Generated by Django 3.2.4 on 2021-07-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0002_achievement_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='achievementlevel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
