# Generated by Django 3.2.4 on 2021-09-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('turn_number', models.IntegerField(blank=True, null=True)),
                ('board_string_representation', models.TextField(blank=True, null=True)),
                ('number_infected', models.IntegerField(blank=True, null=True)),
                ('number_healthy', models.IntegerField(blank=True, null=True)),
                ('number_immune', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
