# Generated by Django 3.2.4 on 2021-09-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celauco', '0002_board_number_of_dead'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_room',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
