# Generated by Django 3.2.4 on 2021-09-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celauco', '0003_board_is_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('game_tag', models.CharField(blank=True, max_length=22, null=True)),
                ('number_healthy', models.TextField(blank=True, null=True)),
                ('number_immune', models.TextField(blank=True, null=True)),
                ('number_infected', models.TextField(blank=True, null=True)),
                ('number_of_dead', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
